[project]
name = "optn"
version = "0.2.0"
description = "Calculate option returns for short puts and covered calls"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Richard Todd", email = "rwtodd@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
optn = "optn:main"

[tool.uv]
package = true

#[build-system]
#requires = ["uv_build>=0.11.16,<0.12.0"]
#build-backend = "uv_build"
