#!/usr/bin/env python3

from pathlib import Path
from sys import argv

for p in (Path(fn) for fn in argv[1:]):
    with open(p,'rb') as infile:
        bs = infile.read(4)
    if bs == b'%PDF':
        p.rename(p.with_suffix('.pdf'))
    else:
        p.rename(p.with_suffix('.epub'))
